### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by dbolser** [docker-android-sdk/android-30#11]
Is there documentation on how to use this image in detail?

e.g. I had to run `apt-get install pulseaudio` and `libxcursor-dev` to get the emulator to pop up a screen, but even then audio didn't work... I'm wondering if that is what this is for?

Should I be using the image to 'run a phone on my screen' or in some more technical way?

I can post a log of errors if that helps. e.g., one among several:
```
WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.
WARNING | cannot add library /opt/android-sdk-linux/emulator/qemu/linux-x86_64/lib64/vulkan/libvulkan.so: failed
```

Thank you for this image, it's a lot of fun to play with (crashes quite a bit though).

Cheers,
Dan.

**Comment by ppoffice** [comment]
It is to be used in CI testings or builds where user interactions are not needed. So display and audio support is not our concern.

**Comment by dbolser** [comment]
I see. However, could be good to add pulseaudio and libxcursor-dev to the Docker setup, just so you can support it :-)

Cheers,
Dan.
