### ISSUE TITLE
On Docker: Not able to launch emulator got error - CPU acceleration status: KVM requires a CPU that supports vmx or svm

### ISSUE THREAD

**Issue by warademilind** [docker-android-sdk/android-30#3]
**On Docker: Not able to launch emulator got error - CPU acceleration status: KVM requires a CPU that supports vmx or svm**

Available Updates:
  ID                                          | Installed | Available
  -------                                     | -------   | -------
  cmdline-tools;latest                        | 2.1       | 4.0
  emulator                                    | 30.1.5    | 30.6.5
  platform-tools                              | 30.0.4    | 31.0.2
  system-images;android-30;google_apis;x86_64 | 8         | 10

root@547e0a3576ac:/opt/android-sdk-linux# avdmanager create avd -n first_avd --abi google_apis/x86_64 -k "system-images;android-30;google_apis;x86_64"
Do you wish to create a custom hardware profile? [no] emote repository...
root@547e0a3576ac:/opt/android-sdk-linux# emulator -avd first_avd -no-window -no-audio &
[1] 113
root@547e0a3576ac:/opt/android-sdk-linux# emulator: ERROR: x86_64 emulation currently requires hardware acceleration!
**CPU acceleration status: KVM requires a CPU that supports vmx or svm**
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.

Windows 10 

Even BIOS is enabled...still error is there.

Can you help me, how to run emulator on Docker?

**Note:** I went through few websites...which tells- 
Emulator
ARM emulator is host machine independent, can run anywhere - Linux, macOS, VM and etc. While the performance is a bit poor. On the contrary, x86 emulator requires KVM, which means only runnable on Linux.

According to Google's documentation:

VM acceleration restrictions

Note the following restrictions of VM acceleration:

You can't run a VM-accelerated emulator inside another VM, such as a VM hosted by VirtualBox, VMWare, or Docker. You must run the emulator directly on your system hardware.

You can't run software that uses another virtualization technology at the same time that you run the accelerated emulator. For example, VirtualBox, VMWare, and Docker currently use a different virtualization technology, so you can't run them at the same time as the accelerated emulator.

**Comment by ppoffice** [comment]
@warademilind What's your host configuration?

**Comment by warademilind** [comment]
> @warademilind What's your host configuration?

Thanks for quick reply.
I am using Windows 10 and trying to run Android Emulator using Docker (taken latest version).

**Comment by ppoffice** [comment]
@warademilind You need to enable KVM in your WSL
