### ISSUE TITLE
Emulator is shown as out of date

### ISSUE THREAD

**Issue by warademilind** [docker-android-sdk/android-30#5]
While executing command - emulator -avd first_avd -no-window -no-audio &
Below error occcured.

root@d23fca28e0be:/opt/android-sdk-linux# emulator -avd first_avd -no-window -no-audio &
[1] 113
root@d23fca28e0be:/opt/android-sdk-linux# emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037
WARNING. Using fallback path for the emulator registration directory.
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

root@d23fca28e0be:/opt/android-sdk-linux# adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
emulator-5554   offline

Can you please help, how to resolve this error?
Your emulator is out of date, please update by launching Android Studio:  
-> Do I need to open Android Studio (which I am using previously) which is installed on my laptop (Windows 10) out side Docker.

**Comment by warademilind** [comment]
Taken latest pull and tried, faced issue:

root@029b8e69ddc1:/opt/android-sdk-linux# emulator -avd first_avd -no-window -no-audio &
[1] 131
root@029b8e69ddc1:/opt/android-sdk-linux# emulator: Android emulator version 30.6.5.0 (build_id 7324830) (CL:N/A)
handleCpuAcceleration: feature check for hvf
emulator: feeding guest with passive gps data, in headless mode
emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037
cannot add library /opt/android-sdk-linux/emulator/qemu/linux-x86_64/lib64/vulkan/libvulkan.so: failed
added library /opt/android-sdk-linux/emulator/lib64/vulkan/libvulkan.so
cannot add library /opt/android-sdk-linux/emulator/lib64/vulkan/libvulkan.so.1: full
emulator: INFO: GrpcServices.cpp:315: Started GRPC server at 127.0.0.1:8554, security: Local
WARNING. Using fallback path for the emulator registration directory.
emulator: INFO: EmulatorAdvertisement.cpp:93: Advertising in: /opt/android-sdk-linux/.android/avd/running/pid_131.ini
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

Can you please help, how to resolve this error?
Your emulator is out of date, please update by launching Android Studio:
-> Do I need to open Android Studio (which I am using previously) which is installed on my laptop (Windows 10) out side Docker.

**Comment by ppoffice** [comment]
@warademilind Those warnings and errors do not prevent you from running the device successfully. Use `adb devices` to see if your AVD is up and running.

**Comment by warademilind** [comment]
> @warademilind Those warnings and errors do not prevent you from running the device successfully. Use `adb devices` to see if your AVD is up and running.

@ppoffice ,
Executed command "adb devices" , able to see emulator as Offline.

root@7d8c328adb65:/opt/android-sdk-linux# emulator -avd first_avd -no-window -no-audio &
[1] 131
root@7d8c328adb65:/opt/android-sdk-linux# emulator: Android emulator version 30.6.5.0 (build_id 7324830) (CL:N/A)
handleCpuAcceleration: feature check for hvf
emulator: feeding guest with passive gps data, in headless mode
emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037
cannot add library /opt/android-sdk-linux/emulator/qemu/linux-x86_64/lib64/vulkan/libvulkan.so: failed
adb devicesadded library /opt/android-sdk-linux/emulator/lib64/vulkan/libvulkan.so
cannot add library /opt/android-sdk-linux/emulator/lib64/vulkan/libvulkan.so.1: full
emulator: INFO: GrpcServices.cpp:315: Started GRPC server at 127.0.0.1:8554, security: Local
WARNING. Using fallback path for the emulator registration directory.
emulator: INFO: EmulatorAdvertisement.cpp:93: Advertising in: /opt/android-sdk-linux/.android/avd/running/pid_131.ini
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

adb devices
adb: unknown command devicesadb
root@7d8c328adb65:/opt/android-sdk-linux# adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
emulator-5554   offline


So executed below commands:
adb -e reboot
adb -Rf ~/.android
adb start-server
adb devices

Now, emulator is online. 

Thanks a lot @ppoffice
