### ISSUE TITLE
Issues with Sysdig scan

### ISSUE THREAD

**Issue by ManasiKher** [docker-android-sdk/android-30#7]
I team, i am using this image for my Gitlab CI. But my company sysdig scan has found the major and medium issues in below frameworks,
1.log4j, 2. protobuf, 3.guava - fix is 23.6.1 24.1.1 25.0, 4. commons-compress, 5.commns-codec.

Is it possible to fix this sysdig scan issues?

**Comment by ppoffice** [comment]
Sorry I am not familiar with sysdig. I think those packages you mentioned are from Android ask. Try modifying the dockerfile and update those packages may help.

**Comment by ManasiKher** [comment]
Thanks, I will try for it
