### ISSUE TITLE
Is it possible to use the image directly on OSX or Windows (WSL 2)?

### ISSUE THREAD

**Issue by Grunet** [docker-android-sdk/android-30#9]
Was just curious if this only works directly on Linux, or if you happened to know of ways to get it working on containers running on top of Docker for Mac/WSL 2 as well (for local testing)

TL;DR

I just tried it on a Mac and ran into a warning when starting the emulator that "kvm" was missing and that hardware acceleration was required. AFAICT from a flurry of google searching OSX doesn't support kvm for virtualization, so I ended up concluding it might not be possible.

I'm in the process of trying it out on WSL 2 but I'm not optimistic about my chances there either given [this outstanding issue around nested virtualization](https://github.com/microsoft/WSL/issues/4193).

Is the only alternative to spin up Linux VMs and run Docker there instead? If not, would love to hear about what folks have done to make it work directly.

Thanks!

**Comment by ppoffice** [comment]
@Grunet If your rig has an Intel CPU that supports nested virtualization, you should be able to enable KVM in WSL2 with a few tweaks. A good starting point would be https://boxofcables.dev/accelerated-kvm-guests-on-wsl-2/.

However, if you are using AMD CPUs, you need to upgrade your some Windows insider preview versions to get AMD nested virtualization support for Hyper-V. And I'm not sure if the above tutorial still works.

**Comment by Grunet** [comment]
Awesome, thank you for the references/information! I'll go ahead and close this since my OG question was answered imo.
